spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:wateroms;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
